<?
$lang_settings['search'] = array('name'=>"Поиск", 'name_en'=>"Search");
$lang_settings['search_site'] = array('name'=>"По сайту", 'name_en'=>"Po situ");
$lang_settings['search_cure'] = array('name'=>"По профилю лечения", 'name_en'=>"Po Profilu lecheniya");
$lang_settings['search_diagnosis'] = array('name'=>"По диагнозу", 'name_en'=>"Po diagnozu");
$lang_settings['free_call'] = array('name'=>"Бесплатный звонок по Росcии", 'name_en'=>"Besplatny zvonok po Rossii");
$lang_settings['region_phone'] = array('name'=>"Региональный номер", 'name_en'=>"Regionalny nomer");
$lang_settings['news'] = array('name'=>"Новости", 'name_en'=>"News");
$lang_settings['spec'] = array('name'=>"Акции ", 'name_en'=>"Akcii ");
$lang_settings['sitemap'] = array('name'=>"Карта сайта", 'name_en'=>"Sitemap");
$lang_settings['faq'] = array('name'=>"Часто задаваемые вопросы", 'name_en'=>"FAQ");
$lang_settings['faq_alert_title'] = array('name'=>"Спасибо за Ваш вопрос!", 'name_en'=>"Thank you for the question");
$lang_settings['faq_alert_text'] = array('name'=>"Мы получили Ваше сообщение и обязательно ответим на него в ближайшее время.", 'name_en'=>"Your question have been sent. We will give you an answer shortly");
$lang_settings['print'] = array('name'=>"Версия для печати", 'name_en'=>"Print page");
$lang_settings['bystroe'] = array('name'=>"Быстрое бронирование", 'name_en'=>"Bystroe bronirovanie");
$lang_settings['san_kur_lechenie'] = array('name'=>"Санаторно-курортное лечение", 'name_en'=>"Sanatorno-kurortnoe lechenie");
$lang_settings['zabolev'] = array('name'=>"Заболевания", 'name_en'=>"Zabolevaniya");
$lang_settings['san_kurort_karta'] = array('name'=>"Санаторно-курортная карта", 'name_en'=>"Sanatorno-kurortnaya karta");
$lang_settings['sanatorii'] = array('name'=>"Санатории ", 'name_en'=>"Sanartorii");
$lang_settings['zhd'] = array('name'=>"Заказ билетов", 'name_en'=>"Zakaz z/d biletov");
$lang_settings['press'] = array('name'=>"пресс-центр", 'name_en'=>"press-center");
$lang_settings['reklamnye'] = array('name'=>"Рекламные материалы", 'name_en'=>"Reklamnye materialy");
$lang_settings['item'] = array('name'=>"Галерея", 'name_en'=>"Galereya");
$lang_settings['video'] = array('name'=>"Видео", 'name_en'=>"Video");
$lang_settings['virtual'] = array('name'=>"Виртуальные туры", 'name_en'=>"Virtualnye tury");
$lang_settings['pdf'] = array('name'=>"Брошюры", 'name_en'=>"Brochure");
$lang_settings['partners'] = array('name'=>"Партнеры", 'name_en'=>"Partners");
$lang_settings['oplata'] = array('name'=>"Оплата путевки", 'name_en'=>"Oplata putevki");
$lang_settings['nashy_san'] = array('name'=>"Наши санатории", 'name_en'=>"Nashy sanatorii");
$lang_settings['media'] = array('name'=>"Библиотека ", 'name_en'=>"Biblioteka");
$lang_settings['more'] = array('name'=>"Подробнее", 'name_en'=>"More");
$lang_settings['zakazat'] = array('name'=>"Заказать путевку", 'name_en'=>"Zakazat putevku");
$lang_settings['opisanie'] = array('name'=>"Описание санатория", 'name_en'=>"Opisanie sanatoriya");
$lang_settings['opinion'] = array('name'=>"Отзывы ", 'name_en'=>"Otzivi");
$lang_settings['ostavit_otziv'] = array('name'=>"Оставить отзыв", 'name_en'=>"Ostavit otziv");
$lang_settings['dobavit_otziv'] = array('name'=>"Добавить отзыв", 'name_en'=>"Dobavit otziv");
$lang_settings['feedback_alert_title'] = array('name'=>"Спасибо за Ваш отзыв!", 'name_en'=>"Thank you for the feedback!");
$lang_settings['feedback_alert_text'] = array('name'=>"Мы получили Ваше сообщение и обязательно ответим на него в ближайшее время.", 'name_en'=>"Your message have been sent. We will give you an answer shortly");
$lang_settings['kogda_otdyh'] = array('name'=>"Когда Вы отдыхали?", 'name_en'=>"Kogda vy otdyhali");
$lang_settings['from'] = array('name'=>"с", 'name_en'=>"s");
$lang_settings['to'] = array('name'=>"по", 'name_en'=>"po");
$lang_settings['vash_otzyv'] = array('name'=>"Ваш отзыв", 'name_en'=>"Vash otziv");
$lang_settings['vse_sanatorii'] = array('name'=>"все санатории", 'name_en'=>"vse sanatorii");
$lang_settings['captcha'] = array('name'=>"Пожалуйста, введите код, указанный на картинке", 'name_en'=>"Please enter the code from the image below");
$lang_settings['captcha1'] = array('name'=>"Цифры на картинке", 'name_en'=>"Verification code");
$lang_settings['captcha2'] = array('name'=>"Цифры", 'name_en'=>"Code");
$lang_settings['sendphone'] = array('name'=>"Отправить", 'name_en'=>"Send");
$lang_settings['404'] = array('name'=>"Ошибка 404", 'name_en'=>"Error 404");
$lang_settings['notfound'] = array('name'=>"Запрашиваемая страница не найдена", 'name_en'=>"The page you have requested is no longer available.");
$lang_settings['home'] = array('name'=>"Главная", 'name_en'=>"Home");
$lang_settings['sitemap'] = array('name'=>"Карта сайта", 'name_en'=>"Sitemap");
$lang_settings['pages'] = array('name'=>"Страницы", 'name_en'=>"Pages");
$lang_settings['favourites'] = array('name'=>" добавить в избранное", 'name_en'=>"add to favorites");
$lang_settings['we_will_call'] = array('name'=>"Мы перезвоним", 'name_en'=>"we'll call you");
$lang_settings['leave_phone'] = array('name'=>"Оставьте свой номер и наши операторы свяжутся с Вами", 'name_en'=>"Please, send your phone number. We will call you back");
$lang_settings['name'] = array('name'=>"Имя", 'name_en'=>"Name");
$lang_settings['phone_number'] = array('name'=>"Телефон", 'name_en'=>"Phone number");
$lang_settings['email'] = array('name'=>"Электронная почта", 'name_en'=>"E-Mail");
$lang_settings['skryt'] = array('name'=>"Скрыть", 'name_en'=>"Skryt");
$lang_settings['raskryt'] = array('name'=>"Раскрыть", 'name_en'=>"Raskryt");
$lang_settings['otvet'] = array('name'=>"Ответ", 'name_en'=>"Answer");
$lang_settings['svernut'] = array('name'=>"Свернуть", 'name_en'=>"Svernut");
$lang_settings['zadaite'] = array('name'=>"Если Вы не нашли ответ на свой вопрос, Вы можете задать его в данной форме.", 'name_en'=>"Zadaite svoi vopros");
$lang_settings['vash_vopros'] = array('name'=>"Ваш вопрос", 'name_en'=>"Vash vopros");
$lang_settings['err_phone'] = array('name'=>"Неверный формат телефона!", 'name_en'=>"Please, check phone");
$lang_settings['err_name'] = array('name'=>"Укажите ваше имя", 'name_en'=>"Please, check your name");
$lang_settings['err_email'] = array('name'=>"Неверно указан электронный адрес", 'name_en'=>"Please, check E-Mail");
$lang_settings['err_captcha'] = array('name'=>"Укажите верно цифры на картинке", 'name_en'=>"Please, check Verification code");
$lang_settings['err_text'] = array('name'=>"Укажите текст сообщения", 'name_en'=>"Ukazhite text");
//$lang_settings['dobavlen_otziv'] = array('name'=>"Сообщение получено. После модерации отзыв будет доступен для чтения.", 'name_en'=>"Vash otziv budet dobavlen v blizhaishee vremya");
//$lang_settings['otvetim'] = array('name'=>"Спасибо! Сообщение получено. В ближайшее время мы ответим на ваш вопрос.", 'name_en'=>"Spasibo, my otvetim");
$lang_settings['close'] = array('name'=>"Закрыть", 'name_en'=>"Close");
$lang_settings['thank'] = array('name'=>"Спасибо!", 'name_en'=>"Thank!");
$lang_settings['our_manager'] = array('name'=>" Наши менеджеры свяжутся с Вами в самое ближайшее время!", 'name_en'=>"We will call you");
$lang_settings['po_zaprosu'] = array('name'=>"По запросу", 'name_en'=>"Po zaprosu");
$lang_settings['naideno'] = array('name'=>"найдено страниц", 'name_en'=>"naideno stranic");
$lang_settings['ne_naideno'] = array('name'=>"ничего не найдено", 'name_en'=>"nichego ne naideno");
$lang_settings['big_quality'] = array('name'=>"Открыть в большом разрешении", 'name_en'=>"Big size image");
$lang_settings['gtema'] = array('name'=>"Вопросы по темам", 'name_en'=>"Temy");
$lang_settings['gtema_choise'] = array('name'=>"Выберите тему вопроса", 'name_en'=>"Viberi");
$lang_settings['medicine'] = array('name'=>"Медицина", 'name_en'=>"Medicine");
$lang_settings['allsan'] = array('name'=>"Все санатории ОАО «РЖД-ЗДОРОВЬЕ»", 'name_en'=>"Vse sanatorii RZD");
$lang_settings['siterzd'] = array('name'=>"Сайт ОАО «РЖД-ЗДОРОВЬЕ»", 'name_en'=>"Sait RZD");
$lang_settings['uvgosti'] = array('name'=>"Уважаемые гости!", 'name_en'=>"Uvazhaemye gosti!");
$lang_settings['kakoplatit'] = array('name'=>"Путевки в здравницы АО «РЖД-ЗДОРОВЬЕ» Вы можете оплатить любым удобным для Вас способом оплаты. Сотрудник компании сообщит Вам номер Вашего счета. В форме «Выберите получателя» выбирается здравница, по которой будет производиться оплата. В форме «Оплатить счет» вводится номер счета. После выбора здравницы и введения номера счета, в форме появится необходимая информация для осуществления платежа.", 'name_en'=>"Putevki v zdravnici...");
$lang_settings['proverkascheta'] = array('name'=>"В данной форме также можно проверить зачисление денежных средств по Вашему счету.", 'name_en'=>"Proverka scheta...");
$lang_settings['weather'] = array('name'=>"Погода в", 'name_en'=>"Weather in");
$lang_settings['2week'] = array('name'=>"Прогноз на 2 недели", 'name_en'=>"2-week forecast");
$lang_settings['kakdobratsya'] = array('name'=>"Как добраться:", 'name_en'=>"Как dobratsya");
$lang_settings['oshibka'] = array('name'=>"Если вы заметили ошибку на этом сайте, просто выделите ее мышью и нажмите ctrl+enter на клавиатуре.", 'name_en'=>"Esli zametili oshibku");
$lang_settings['allrights'] = array('name'=>'АО "РЖД-ЗДОРОВЬЕ", 2015 все права защищены', 'name_en'=>"All rights");
$lang_settings['razrabotka'] = array('name'=>"Разработка сайта", 'name_en'=>"Made in");
$lang_settings['cureprofile'] = array('name'=>"Медицинский профиль", 'name_en'=>"Profile");
$lang_settings['price'] = array('name'=>"Стоимость в рублях, (Р)", 'name_en'=>"Price, (Р).");
$lang_settings['development'] = array('name'=>"страница в стадии разработки", 'name_en'=>"the page is under development");
?>