<?
$lang_settings['search'] = array('name'=>"Поиск", 'name_en'=>"Search", 'title'=>'Поиск');
$lang_settings['search_site'] = array('name'=>"По сайту", 'name_en'=>"Po situ", 'title'=>'По сайту');
$lang_settings['search_cure'] = array('name'=>"По профилю лечения", 'name_en'=>"Po Profilu lecheniya", 'title'=>'По профилю ');
$lang_settings['search_diagnosis'] = array('name'=>"По диагнозу", 'name_en'=>"Po diagnozu", 'title'=>'По диагнозу');
$lang_settings['free_call'] = array('name'=>"Бесплатный звонок по Росcии", 'name_en'=>"Besplatny zvonok po Rossii", 'title'=>'Текст для номера 8-800');
$lang_settings['region_phone'] = array('name'=>"Региональный номер", 'name_en'=>"Regionalny nomer", 'title'=>'Текст для регионального номера');
$lang_settings['news'] = array('name'=>"Новости", 'name_en'=>"News", 'title'=>'Раздел Новости');
$lang_settings['spec'] = array('name'=>"Акции ", 'name_en'=>"Akcii ", 'title'=>'Раздел Акции');
$lang_settings['sitemap'] = array('name'=>"Карта сайта", 'name_en'=>"Sitemap", 'title'=>'Карта сайта');
$lang_settings['faq'] = array('name'=>"Часто задаваемые вопросы", 'name_en'=>"FAQ", 'title'=>'Раздел FAQ');
$lang_settings['print'] = array('name'=>"Версия для печати", 'name_en'=>"Print page", 'title'=>'Ссылка "Версия для печати"');
$lang_settings['bystroe'] = array('name'=>"Быстрое бронирование", 'name_en'=>"Bystroe bronirovanie", 'title'=>'Кнопка "быстрое бронирование"');
$lang_settings['san_kur_lechenie'] = array('name'=>"Санаторно-курортное лечение", 'name_en'=>"Sanatorno-kurortnoe lechenie", 'title'=>'Кнопка "Санаторно-курортное лечение" на главной');
$lang_settings['zabolev'] = array('name'=>"Заболевания", 'name_en'=>"Zabolevaniya", 'title'=>'Кнопка "Заболевнаия" на главной');
$lang_settings['san_kurort_karta'] = array('name'=>"Санаторно-курортная карта", 'name_en'=>"Sanatorno-kurortnaya karta", 'title'=>'Кнопка "Санаторно-курортная карта" на главной');
$lang_settings['sanatorii'] = array('name'=>"Санатории ", 'name_en'=>"Sanartorii", 'title'=>'Раздел Санатории');
$lang_settings['zhd'] = array('name'=>"Заказ билетов", 'name_en'=>"Zakaz z/d biletov", 'title'=>'Раздел Заказ билетов');
$lang_settings['press'] = array('name'=>"пресс-центр", 'name_en'=>"press-center", 'title'=>'Раздел Пресс-центр');
$lang_settings['reklamnye'] = array('name'=>"Рекламные материалы", 'name_en'=>"Reklamnye materialy", 'title'=>'Рекламные материалы');
$lang_settings['item'] = array('name'=>"Галерея", 'name_en'=>"Galereya", 'title'=>'Галерея (для библиотеки)');
$lang_settings['video'] = array('name'=>"Видео", 'name_en'=>"Video", 'title'=>'Видео (для библиотеки)');
$lang_settings['virtual'] = array('name'=>"Виртуальные туры", 'name_en'=>"Virtualnye tury", 'title'=>'Вирутальные туры (для библиотеки)');
$lang_settings['pdf'] = array('name'=>"Брошюры", 'name_en'=>"Brochure", 'title'=>'Брошюры (для библиотеки)');
$lang_settings['partners'] = array('name'=>"Партнеры", 'name_en'=>"Partners", 'title'=>'Раздел Партнёры');
$lang_settings['oplata'] = array('name'=>"Оплата путевки", 'name_en'=>"Oplata putevki", 'title'=>'Оплата путевки');
$lang_settings['nashy_san'] = array('name'=>"Наши санатории", 'name_en'=>"Nashy sanatorii", 'title'=>'Наши санатории');
$lang_settings['media'] = array('name'=>"Библиотека ", 'name_en'=>"Biblioteka", 'title'=>'Библиотека');
$lang_settings['more'] = array('name'=>"Подробнее", 'name_en'=>"More", 'title'=>'Кнопка "Подробнее"');
$lang_settings['zakazat'] = array('name'=>"Заказать путевку", 'name_en'=>"Zakazat putevku", 'title'=>'Для заказа путевки');
$lang_settings['opisanie'] = array('name'=>"Описание санатория", 'name_en'=>"Opisanie sanatoriya", 'title'=>'Описание санатория');
$lang_settings['opinion'] = array('name'=>"Отзывы ", 'name_en'=>"Otzivi", 'title'=>'Для страницы отзывов');
$lang_settings['ostavit_otziv'] = array('name'=>"Оставить отзыв", 'name_en'=>"Ostavit otziv", 'title'=>'Для страницы отзывов');
$lang_settings['dobavit_otziv'] = array('name'=>"Добавить отзыв", 'name_en'=>"Dobavit otziv", 'title'=>'Для страницы отзывов');
$lang_settings['kogda_otdyh'] = array('name'=>"Когда Вы отдыхали?", 'name_en'=>"Kogda vy otdyhali", 'title'=>'Для страницы отзывов');
$lang_settings['from'] = array('name'=>"с", 'name_en'=>"s", 'title'=>'Для страницы отзывов');
$lang_settings['to'] = array('name'=>"по", 'name_en'=>"po", 'title'=>'Для страницы отзывов');
$lang_settings['vash_otzyv'] = array('name'=>"Ваш отзыв", 'name_en'=>"Vash otziv", 'title'=>'Для страницы отзывов');
$lang_settings['vse_sanatorii'] = array('name'=>"все санатории", 'name_en'=>"vse sanatorii", 'title'=>'Все санатории');
$lang_settings['captcha'] = array('name'=>"Пожалуйста, введите код, указанный на картинке", 'name_en'=>"Please enter the code from the image below", 'title'=>'Защита от спама');
$lang_settings['captcha1'] = array('name'=>"Цифры на картинке", 'name_en'=>"Verification code", 'title'=>'Защита от спама');
$lang_settings['captcha2'] = array('name'=>"Цифры", 'name_en'=>"Code", 'title'=>'Защита от спама');
$lang_settings['sendphone'] = array('name'=>"Отправить", 'name_en'=>"Send", 'title'=>'Для отправки номера телефона');
$lang_settings['404'] = array('name'=>"Ошибка 404", 'name_en'=>"Error 404", 'title'=>'Ошибка 404');
$lang_settings['notfound'] = array('name'=>"Запрашиваемая страница не найдена", 'name_en'=>"The page you have requested is no longer available.", 'title'=>'Ошибка 404');
$lang_settings['home'] = array('name'=>"Главная", 'name_en'=>"Home", 'title'=>'Главная');
$lang_settings['sitemap'] = array('name'=>"Карта сайта", 'name_en'=>"Sitemap", 'title'=>'Карта сайта');
$lang_settings['pages'] = array('name'=>"Страницы", 'name_en'=>"Pages", 'title'=>'Страницы');
$lang_settings['favourites'] = array('name'=>" добавить в избранное", 'name_en'=>"add to favorites", 'title'=>'Кнопка "Избранное"');
$lang_settings['we_will_call'] = array('name'=>"Мы перезвоним", 'name_en'=>"we'll call you", 'title'=>'Ответ на оставленный номер телефона');
$lang_settings['leave_phone'] = array('name'=>"Оставьте свой номер и наши операторы свяжутся с Вами", 'name_en'=>"Please, send your phone number. We will call you back", 'title'=>'Ответ на оставленный номер телефона');
$lang_settings['name'] = array('name'=>"Имя", 'name_en'=>"Name", 'title'=>'Для формы отправки сообщения');
$lang_settings['phone_number'] = array('name'=>"Телефон", 'name_en'=>"Phone number", 'title'=>'Для формы отправки сообщения');
$lang_settings['email'] = array('name'=>"Электронная почта", 'name_en'=>"E-Mail", 'title'=>'Для формы отправки сообщения');
$lang_settings['skryt'] = array('name'=>"Скрыть", 'name_en'=>"Skryt", 'title'=>'Для страницы FAQ');
$lang_settings['raskryt'] = array('name'=>"Раскрыть", 'name_en'=>"Raskryt", 'title'=>'Для страницы FAQ');
$lang_settings['otvet'] = array('name'=>"Ответ", 'name_en'=>"Answer", 'title'=>'Для страницы FAQ');
$lang_settings['svernut'] = array('name'=>"Свернуть", 'name_en'=>"Svernut", 'title'=>'Для страницы FAQ');
$lang_settings['zadaite'] = array('name'=>"Если Вы не нашли ответ на свой вопрос, Вы можете задать его в данной форме.", 'name_en'=>"Zadaite svoi vopros", 'title'=>'Для страницы FAQ');
$lang_settings['vash_vopros'] = array('name'=>"Ваш вопрос", 'name_en'=>"Vash vopros", 'title'=>'Для страницы FAQ');
$lang_settings['err_phone'] = array('name'=>"Неверный формат телефона!", 'name_en'=>"Please, check phone", 'title'=>'Текст ошибки при отправки телефона');
$lang_settings['err_name'] = array('name'=>"Укажите ваше имя", 'name_en'=>"Please, check your name", 'title'=>'Текст ошибки при отправки сообщения');
$lang_settings['err_email'] = array('name'=>"Неверно указан электронный адрес", 'name_en'=>"Please, check E-Mail", 'title'=>'Текст ошибки при отправки сообщения');
$lang_settings['err_captcha'] = array('name'=>"Укажите верно цифры на картинке", 'name_en'=>"Please, check Verification code", 'title'=>'Текст ошибки при отправки сообщения');
$lang_settings['err_text'] = array('name'=>"Укажите текст сообщения", 'name_en'=>"Ukazhite text", 'title'=>'Текст ошибки при отправки сообщения');
$lang_settings['close'] = array('name'=>"Закрыть", 'name_en'=>"Close", 'title'=>'Закрыть');
$lang_settings['thank'] = array('name'=>"Спасибо!", 'name_en'=>"Thank!", 'title'=>'Ответ на оставленный телефон или сообщение');
$lang_settings['our_manager'] = array('name'=>" Наши менеджеры свяжутся с Вами в самое ближайшее время!", 'name_en'=>"We will call you", 'title'=>'Ответ на оставленный номер телефона');
$lang_settings['po_zaprosu'] = array('name'=>"По запросу", 'name_en'=>"Po zaprosu", 'title'=>'По запросу');
$lang_settings['naideno'] = array('name'=>"найдено страниц", 'name_en'=>"naideno stranic", 'title'=>'Положительный результат поиска по сайту');
$lang_settings['ne_naideno'] = array('name'=>"ничего не найдено", 'name_en'=>"nichego ne naideno", 'title'=>'Отрицательный результат поиска по сайту');
$lang_settings['big_quality'] = array('name'=>"Открыть в большом разрешении", 'name_en'=>"Big size image", 'title'=>'Для фотографий');
$lang_settings['gtema'] = array('name'=>"Вопросы по темам", 'name_en'=>"Temy", 'title'=>'Для страницы FAQ');
$lang_settings['gtema_choise'] = array('name'=>"Выберите тему вопроса", 'name_en'=>"Viberi", 'title'=>'Для страницы FAQ');
$lang_settings['medicine'] = array('name'=>"Медицина", 'name_en'=>"Medicine", 'title'=>'Медицина');
$lang_settings['allsan'] = array('name'=>"Все санатории ОАО «РЖД-ЗДОРОВЬЕ»", 'name_en'=>"Vse sanatorii RZD", 'title'=>'Для ссылки на сонвоной сайт с сайтов филиалов');
$lang_settings['siterzd'] = array('name'=>"Сайт ОАО «РЖД-ЗДОРОВЬЕ»", 'name_en'=>"Sait RZD", 'title'=>'Для ссылки на сонвоной сайт с сайтов филиалов');
$lang_settings['uvgosti'] = array('name'=>"Уважаемые гости!", 'name_en'=>"Uvazhaemye gosti!", 'title'=>'Для формы оплаты в подвале');
$lang_settings['kakoplatit'] = array('name'=>"Путевки в здравницы АО «РЖД-ЗДОРОВЬЕ» Вы можете оплатить любым удобным для Вас способом оплаты. Сотрудник компании сообщит Вам номер Вашего счета. В форме «Выберите получателя» выбирается здравница, по которой будет производиться оплата. В форме «Оплатить счет» вводится номер счета. После выбора здравницы и введения номера счета, в форме появится необходимая информация для осуществления платежа.", 'name_en'=>"Putevki v zdravnici...", 'title'=>'Для формы оплаты в подвале');
$lang_settings['proverkascheta'] = array('name'=>"В данной форме также можно проверить зачисление денежных средств по Вашему счету.", 'name_en'=>"Proverka scheta...", 'title'=>'Для формы проверки счёта в подвале');
$lang_settings['weather'] = array('name'=>"Погода в", 'name_en'=>"Weather in", 'title'=>'Для информера прогноза погоды');
$lang_settings['2week'] = array('name'=>"Прогноз на 2 недели", 'name_en'=>"2-week forecast", 'title'=>'Для информера прогноза погоды');
$lang_settings['kakdobratsya'] = array('name'=>"Как добраться:", 'name_en'=>"Как dobratsya", 'title'=>'Для блока "Как добраться" в подвале');
$lang_settings['oshibka'] = array('name'=>"Если вы заметили ошибку на этом сайте, просто выделите ее мышью и нажмите ctrl+enter на клавиатуре.", 'name_en'=>"Esli zametili oshibku", 'title'=>'Для блока "Если вы заметили ошибку" в подвале');
$lang_settings['allrights'] = array('name'=>"АО \"РЖД-ЗДОРОВЬЕ\", 2015 все права защищены", 'name_en'=>"All rights", 'title'=>'Копирайт в подвале');
$lang_settings['allrights1'] = array('name'=>"Воспроизведение или распространение материалов в любой форме может производиться только с письменного разрешения АО \"РЖД-ЗДОРОВЬЕ\". При использовании ссылка на правообладателя и источник заимствования обязательна.", 'name_en'=>"Copy is prohibited", 'title'=>'Копирайт в подвале-2');
$lang_settings['razrabotka'] = array('name'=>"Разработка сайта", 'name_en'=>"Made in", 'title'=>'Сведения о разработке сайта');
$lang_settings['cureprofile'] = array('name'=>"Медицинский профиль", 'name_en'=>"Profile", 'title'=>'Медицинский профиль');
$lang_settings['price'] = array('name'=>"Стоимость в рублях, (Р)", 'name_en'=>"Price, (Р).", 'title'=>'Для заголовка прайс-листа');
$lang_settings['development'] = array('name'=>"страница в стадии разработки", 'name_en'=>"the page is under development", 'title'=>'Текст для страницы в стадии разработки');
$lang_settings['feedback_alert_title'] = array('name'=>"Спасибо за Ваш отзыв!", 'name_en'=>"Thank you for the feedback!", 'title'=>'Заголовок сообщения посетителю после отправки отзыва');
$lang_settings['feedback_alert_text'] = array('name'=>"Мы получили Ваше сообщение и обязательно ответим на него в ближайшее время.", 'name_en'=>"Your message have been sent. We will give you an answer shortly", 'title'=>'Сообщение посетителю после отправки отзыва');
$lang_settings['faq_alert_title'] = array('name'=>"Спасибо за Ваш вопрос!", 'name_en'=>"Thank you for the question", 'title'=>'Заголовок сообщения посетителю после отправки вопроса');
$lang_settings['faq_alert_text'] = array('name'=>"Мы получили Ваше сообщение и обязательно ответим на него в ближайшее время.", 'name_en'=>"Your question have been sent. We will give you an answer shortly", 'title'=>'Сообщение посетителю после отправки вопроса');
$lang_settings['vrazrabotke'] = array('name'=>"Раздел находится в разработке", 'name_en'=>"V razrabotke", 'title'=>'Текст для раздела в стадии разработки');
$lang_settings['summer'] = array('name'=>3, 'name_en'=>"9", 'title'=>'Сезонность для мета-тегов. Первое поле – порядковый номер месяца начала лета, второе – зимы');